### ISSUE TITLE
Select2 version 4

### ISSUE THREAD

**Issue by mhluzi** [themepixels/select2-skins#1]
Hi 
I am using Select2 version 4 and can't get this to work.

Is it configured to work with version 4?

Regard

M.

**Comment by mhluzi** [comment]
I am presuming so as I see on http://ui.themepixels.com/select2-skins/bower_components/select2/select2.css the version of select2 is Version: 3.5.2 

Is there a skins planned for Select2 version 4?

**Comment by themepixels** [comment]
The skin is for Select2 version 3.5. If given enough time I will create skin for version 4. Thanks

**Comment by mhluzi** [comment]
Thanks themepixels!

**Comment by champsupertramp** [comment]
+1

**Comment by dikiaap** [comment]
@themepixels Hem, I think you should update readme. Because only select2 version 3.5 support this skins :|
